### PR TITLE
incusd/device/nic_bridged: Handle physical NICs

### LINKED ISSUE #3155: Invalid devices: Device validation failed for "eth-1": Specified network must be of type bridge
I have a few VMs that won't start after a reboot, they're all assigned physical network interfaces. This error has only happened as of my last reboot, all were working fine for a few weeks at least prior.

All have the same error (in title) and an example VM config is as follows:

```
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Ubuntu noble amd64 (20260227_10:13)
  image.os: Ubuntu
  image.release: noble
  image.requirements.cgroup: v2
  image.serial: '20260227_10:13'
  image.type: squashfs
  image.variant: default
  limits.cpu: '1'
  limits.memory: 1GiB
  security.nesting: 'false'
  security.privileged: 'false'
  security.protection.delete: 'true'
  volatile.base_image: 045457956574067f57f6e5d85bf12b36a179d5793ded8661f3eaef9018cdc3f5
  volatile.cloud-init.instance-id: cf7f2894-efc9-4492-bc5b-f55f53a0fab8
  volatile.eth-1.host_name: veth62b84899
  volatile.eth-1.name: eth0
  volatile.idmap.base: '0'
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
  volatile.uuid: 9793527d-afe5-4b87-bf0e-f80f4d4b0b07
  volatile.uuid.generation: 9793527d-afe5-4b87-bf0e-f80f4d4b0b07
devices:
  eth-1:
    hwaddr: 10:66:6a:0b:62:cf
    network: eno1
    type: nic
  ups-1:
    mode: '0666'
    productid: '0501'
    type: usb
    vendorid: '0764'
ephemeral: false
profiles:
  - default
stateful: false
description: Pie CyberPower VP1000LCD UPS Monitor (AU)
created_at: '2026-02-28T05:09:25.155224324Z'
name: cyberpower-vp1000lcd
status: Stopped
status_code: 102
last_used_at: '2026-03-16T06:04:54.176260389Z'
location: none
type: container
project: default
```

OS Network:
```
time:
  timezone: Australia/Sydney
interfaces:
  - addresses:
      - dhcp4
      - slaac
    hwaddr: c8:ff:bf:01:52:e0
    name: eno1
    required_for_online: 'no'
    roles:
      - instances
  - addresses:
      - dhcp4
      - slaac
    hwaddr: c8:ff:bf:01:52:e1
    name: enp3s0
    required_for_online: 'no'
    roles:
      - instances
```

```
max.schaefer@MacBook-Pro ~> incus network list
+----------+----------+---------+-----------------+---------------------------+----------------------------+---------+---------+
|   NAME   |   TYPE   | MANAGED |      IPV4       |           IPV6            |        DESCRIPTION         | USED BY |  STATE  |
+----------+----------+---------+-----------------+---------------------------+----------------------------+---------+---------+
| eno1     | physical | YES     |                 |                           |                            | 2       | CREATED |
+----------+----------+---------+-----------------+---------------------------+----------------------------+---------+---------+
| enp3s0   | physical | YES     |                 |                           |                            | 1       | CREATED |
+----------+----------+---------+-----------------+---------------------------+----------------------------+---------+---------+
| incusbr0 | bridge   | YES     | 10.134.196.1/24 | fd42:44b2:d5ab:dd70::1/64 | Local Network Bridge (NAT) | 0       | CREATED |
+----------+----------+---------+-----------------+---------------------------+----------------------------+---------+---------+
```

These were set up with this tutorial: https://linuxcontainers.org/incus-os/docs/main/tutorials/network-direct-attach/

This is quite an unfortunate issue at the moment as my NAS and Home Assistant VMs can't come online - if there's any pointers/tips I'd genuinely really appreciate them 🙏🏻

### PR DESCRIPTION
**Pull request by stgraber**
Physical NICs now can jump into the bridged NIC logic for config validation. We therefore can't solely rely on the NIC type during validation anymore.

This is the missing piece to getting physical NICs behaving normally again. This was missed in the most recent fix due to testing happening on pre-existing instances and therefore not running through full validation.

Closes #3155

### CODE REVIEW

**Review by presztak — APPROVED** [review]

File: internal/server/device/nic_bridged.go [hunk 1]
```diff
@@ -342,8 +342,8 @@ func (d *nicBridged) validateConfig(instConf instance.ConfigReader, partialValid
 			return errors.New("Specified network is not fully created")
 		}
 
-		if n.Type() != "bridge" {
-			return errors.New("Specified network must be of type bridge")
+		if n.Type() != "bridge" && (n.Type() != "physical" || !util.PathExists(fmt.Sprintf("/sys/class/net/%s/bridge", d.config["parent"]))) {
+			return fmt.Errorf("Specified network must be of type bridge, %+v", n)
```
Comment (bensmrs) [inline internal/server/device/nic_bridged.go]: Isn’t `, %+v` a leftover from debugging?

Comment (stgraber) [reply internal/server/device/nic_bridged.go]: yep

Comment (stgraber) [reply internal/server/device/nic_bridged.go]: Fixed!
