### PR TITLE
tests: Add incus-user test

### LINKED ISSUE #142: Add test for incus-user
We just had a regression in `incus-user` which really should have been caught prior to release.
This highlighted the fact that this daemon is completely untested and entirely relies on manual testing pre-release.

We should add a basic test to the testsuite which spawns incus-user and attempts to interact with Incus from an unprivileged user to validate its behavior.

### PR DESCRIPTION
**Pull request by stgraber**
Closes #142

### CODE REVIEW

File: test/suites/incus_user.sh [hunk 1]
```diff
@@ -0,0 +1,17 @@
+test_incus_user() {
+  ensure_import_testimage
+  ensure_has_localhost_remote "${INCUS_ADDR}"
+
+  incus-user --group nogroup &
+  USER_PID="$!"
+  sleep 3
```
Comment (hallyn) [inline test/suites/incus_user.sh:7]: Seems fragile - given how slow github runners can sometimes be, it would seem worth checking availability over the socket in a loop, if possible.

**Review by hallyn — APPROVED** [review]
Approving anyway, as the comment was just a suggestion.  Leaving it to you to merge though, if you want to skip the suggestion.

File: test/suites/incus_user.sh [hunk 2]
```diff
@@ -0,0 +1,19 @@
+test_incus_user() {
+  ensure_import_testimage
+  ensure_has_localhost_remote "${INCUS_ADDR}"
+
+  incus-user --group nogroup &
+  USER_PID="$!"
+  while :; do
+    [ -S "${INCUS_DIR}/unix.socket.user" ] && break
```
Comment (hallyn) [inline test/suites/incus_user.sh:8]: (sorry) well, that will spin pretty hard.  Can you add a sleep 0.5s in there or something?  The idea isn't to get past this as fast as possible, but rather to avoid getting to the later commands before it's ready.

Comment (stgraber) [reply test/suites/incus_user.sh:8]: oops, yeah, I meant for a 0.5 :)

Comment (stgraber) [reply test/suites/incus_user.sh:8]: Fixed

**Review by hallyn — APPROVED** [review]
