### PR TITLE
incusd/storage/drivers/common: Truncate/Discard ahead of sparse write

### LINKED ISSUE #1264: Issues while moving instances with snapshot from one storage to another
# Required information

 * Distribution: Debian
 * Distribution version: 12 (bookworm)
 * The output of "incus info" or if that fails:
   * Kernel version: 6.1.0-25-amd64
   * Incus version: 6.5
   * Storage backend in use: btrfs and zfs (see below)

# Issue description

While installing `lxd` some years ago I used a **btrfs** backend for storage. I wanted to try **zfs** so I created one and wanted to [move](https://linuxcontainers.org/incus/docs/main/howto/storage_move_volume/#storage-move-instance) my instances to the latest one, but my instances did not want to start properly.

## storages details

```
$ incus storage show lxc-storage | head -6
config:
  size: 150GiB
  source: /var/lib/incus/disks/lxc-storage.img
description: ""
name: lxc-storage
driver: btrfs
$ incus storage show incus-zfs | head -7
config:
  size: 60GiB
  source: /var/lib/incus/disks/incus-zfs.img
  zfs.pool_name: incus-zfs
description: ""
name: incus-zfs
driver: zfs
```

# Steps to reproduce

## without snapshots

Everything seems to be :+1: 
```
$ incus launch images:debian/12 my-debian --vm
Launching my-debian
$ incus exec my-debian hostname
my-debian
$ incus stop my-debian
$ incus move my-debian --storage incus-zfs
$ incus start my-debian
$ incus exec my-debian hostname
my-debian
```
## with snapshots

Something went bad
```
$ incus launch images:debian/12 my-debian --vm
Launching my-debian
$ incus exec my-debian hostname
my-debian
$ incus stop my-debian
$ incus snapshot create my-debian clean-install
$ incus snapshot list my-debian
+---------------+-----------------------+------------+----------+
|      NOM      |       TAKEN AT        | EXPIRES AT | STATEFUL |
+---------------+-----------------------+------------+----------+
| clean-install | 2024/09/29 19:08 CEST |            | NO       |
+---------------+-----------------------+------------+----------+
$ incus move my-debian --storage incus-zfs
$ incus start my-debian
$ incus exec my-debian hostname
Error: VM agent isn't currently running
$ incus console my-debian --type=vga
$ incus stop my-debian --force
$ incus move my-debian --storage lxc-storage
$ incus start my-debian
$ incus exec my-debian hostname
Error: VM agent isn't currently running
$ incus console my-debian --type=vga
$ incus stop my-debian --force
```

# Information to attach

The cropped snapshots of th console : 
Console 1
Console 2

### PR DESCRIPTION
**Pull request by stgraber**
As we use a sparse writer which will skip any zero blocks, we need to discard (block) or truncate (file) prior to processing the data or we risk having leftover data from a previous snapshot interfere with the new state.

Closes #1264

### CODE REVIEW

File: internal/server/storage/drivers/generic_vfs.go [hunk 1]
```diff
@@ -332,6 +333,36 @@ func genericVFSCreateVolumeFromMigration(d Driver, initVolume func(vol Volume) (
 
 		defer func() { _ = to.Close() }()
 
+		st, err := to.Stat()
```
Comment (hallyn) [inline internal/server/storage/drivers/generic_vfs.go:336]: These two blocks are identical, right?  Any reason not to use a common helper?  Seems like future you will want that.

Comment (stgraber) [reply internal/server/storage/drivers/generic_vfs.go]: @hallyn fair point, updated :)

**Review by hallyn — APPROVED** [review]
